INSERT INTO genre VALUES (10, "Hard Rock");
INSERT INTO genre VALUES (11, "Soundtrack");
INSERT INTO genre VALUES (12, "Pop Rock");
INSERT INTO genre VALUES (13, "Synthpop");
INSERT INTO genre VALUES (14, "Rock Expérimental");
INSERT INTO genre VALUES (15, "Rock Progressif");
INSERT INTO genre VALUES (16, "Rock Symphonique");
INSERT INTO genre VALUES (17, "New Wave");
INSERT INTO genre VALUES (18, "Dance");
INSERT INTO genre VALUES (19, "Electro swing");
INSERT INTO genre VALUES (20, "Alternative");
INSERT INTO genre VALUES (21, "Indie Rock");
INSERT INTO genre VALUES (22, "Folk Rock");
INSERT INTO genre VALUES (23, "Garage Rock");
INSERT INTO genre VALUES (24, "Blues Rock");
INSERT INTO genre VALUES (25, "Dance-Rock");
INSERT INTO genre VALUES (26, "Classic Rock");
INSERT INTO genre VALUES (27, "Hip-hop/Rap");
INSERT INTO genre VALUES (28, "Rock Alternatif");
INSERT INTO genre VALUES (29, "Funk Rock");
INSERT INTO genre VALUES (30, "French Pop");
INSERT INTO genre VALUES (31, "Comédies musicales");
INSERT INTO genre VALUES (32, "Art Rock");
INSERT INTO genre VALUES (33, "Dubstep");
INSERT INTO genre VALUES (34, "Metal Alternatif");
INSERT INTO genre VALUES (35, "Musique Alternative/Indé");
INSERT INTO genre VALUES (36, "New Prog");
INSERT INTO genre VALUES (37, "RnB");
INSERT INTO genre VALUES (38, "Dance Alternative");
INSERT INTO genre VALUES (39, "Grunge");
INSERT INTO genre VALUES (40, "Rock indépendant");
INSERT INTO genre VALUES (41, "Punk Rock");
INSERT INTO genre VALUES (42, "Punk");
INSERT INTO genre VALUES (43, "Heavy Metal");
INSERT INTO genre VALUES (44, "Country Folk");
INSERT INTO genre VALUES (45, "Rock Progressif et Symphonique");
INSERT INTO genre VALUES (46, "Rockabilly");
INSERT INTO genre VALUES (47, "House");
INSERT INTO genre VALUES (48, "Glam Rock");
INSERT INTO genre VALUES (49, "Ballade");
INSERT INTO genre VALUES (50, "Hymne");
INSERT INTO genre VALUES (51, "Music Hall");
INSERT INTO genre VALUES (52, "Gospel");
INSERT INTO genre VALUES (53, "Power Pop");
INSERT INTO genre VALUES (54, "Soul");
INSERT INTO genre VALUES (55, "Arena Rock");
INSERT INTO genre VALUES (56, "Rock Electronique");
INSERT INTO genre VALUES (57, "Opéra-Rock");
INSERT INTO genre VALUES (58, "Power Ballade");
INSERT INTO genre VALUES (59, "Christian Rock");
INSERT INTO genre VALUES (60, "Metal progressif");
INSERT INTO genre VALUES (61, "Chrétien contemporain");
INSERT INTO genre VALUES (62, "Indie");
INSERT INTO genre VALUES (63, "Nu Metal");
INSERT INTO genre VALUES (64, "Chanson enfantine");
INSERT INTO genre VALUES (65, "Beat");
INSERT INTO genre VALUES (66, "Rock Psychédélique");
INSERT INTO genre VALUES (67, "Folk");
INSERT INTO genre VALUES (68, "Space Rock");
INSERT INTO genre VALUES (69, "Skiffle");
INSERT INTO genre VALUES (70, "Hip-hop");
INSERT INTO genre VALUES (71, "Flamenco");
INSERT INTO genre VALUES (72, "Thrash Metal");
INSERT INTO genre VALUES (73, "Musique expérimentale");
